delete from games_genres
where Genre = 'Utilities'
    or Gerne = 'Animation & Modeling'
    or Gerne = 'Video Production' 
    or Gerne = 'Photo Editing'
    or Gerne = 'Design & Illustration'
    or Gerne = 'Education'
    or Gerne = 'Software Training'
    or Gerne = 'Web Publishing'
    or Gerne = 'Audio Production'
    or Gerne = 'Accounting'